eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#security:
 # basic:
  #  enabled: true         # 开启基于HTTP basic的认证
  #user:
  #  name: user            # 登录用户
   # password: 123         # 密码
server:
  port: 8764
spring:
  application:
    name: Xc-Customer-Service