eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#security:
 # basic:
  #  enabled: true         # 开启基于HTTP basic的认证
  #user:
  #  name: user            # 登录用户
   # password: 123         # 密码
server:
  port: 8766
spring:
  application:
    name: Xc-Customer-Service
  ## rabbitmq config
  rabbitmq: 
    host: localhost
    port: 5672
    #username: guest
    #password: guest
  ## database
 
  datasource: 
    url: jdbc:mysql://localhost:3306/cx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    ### spring data jpa
  jpa: 
   hibernate:
    ddl-auto: update  # 第一次建立表create  后面用update
    dialect: org.hibernate.dialect.MySQL5Dialect
   show-sql: true
        
# 格式化输出jackson字符串
    
### config service center
  cloud:
    config:
      label: develop
      profile: dev
      #uri: http://localhost:8888/
      discovery:
        enabled: true #开启配置中心读取配置文件
        service-id: cx-config-server # 配置中心服务名
  jackson:
    serialization:
      indent-output: false
      
management:
  security:
    enabled: false
    
adminPath: /customer

  
        
        
